<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SALIK" failures="1" tests="4" name="com.frameworks.projectCMS.testcases.SigninTest" time="50.086" errors="0" timestamp="2025-04-15T21:15:18 IST" skipped="0">
  <testcase classname="com.frameworks.projectCMS.testcases.SigninTest" name="testSuccessfulllogin" time="13.887"/>
  <testcase classname="com.frameworks.projectCMS.testcases.SigninTest" name="testWithInvalidEmail" time="10.635"/>
  <testcase classname="com.frameworks.projectCMS.testcases.SigninTest" name="navigateToforgotPasswordPage" time="14.673"/>
  <testcase classname="com.frameworks.projectCMS.testcases.SigninTest" name="checkLoginLoadTime" time="10.891">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.frameworks.projectCMS.pages.SigninPage.calculateLoginTime(SigninPage.java:85)
at com.frameworks.projectCMS.testcases.SigninTest.checkLoginLoadTime(SigninTest.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- checkLoginLoadTime -->
</testsuite> <!-- com.frameworks.projectCMS.testcases.SigninTest -->
